/**
 * Jest setupFilesAfterEnv — runs in the test worker after the test framework
 * is installed, before any test suite executes.
 *
 * Registers a synchronous process 'exit' handler to explicitly close all
 * better-sqlite3 database handles. This prevents the native addon from firing
 * its V8 destructor after Jest tears down the isolate, which causes:
 *   Assertion failed: (env) != nullptr  (SIGABRT / exit 134)
 * on Node 24 when fake timers or mocked process.exit interact with the GC.
 *
 * Also configures jest-openapi with the generated OpenAPI spec so that any
 * test can call `expect(response).toSatisfyApiSpec()` without additional setup.
 */

import path from 'path';
import jestOpenAPI from 'jest-openapi';
import { closeAgentDb } from '../src/db/agents';
import { closeTaskDb } from '../src/db/tasks';

// Load the generated OpenAPI spec once for the entire test suite.
// The spec is generated by `npm run docs:generate` and committed to the repo.
jestOpenAPI(path.join(__dirname, '../docs/openapi.yaml'));

// Synchronous exit handler — runs before the V8 isolate is torn down.
process.on('exit', () => {
  try { closeAgentDb(); } catch { /* not opened in this worker */ }
  try { closeTaskDb(); } catch { /* not opened in this worker */ }
});
